{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Lista de espécies Pokémon nomeados por geração[32]\",\"Lista[editar | editar código-fonte]\",\"Table 4\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.1052.0 (23.12)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "Lista de espécies Pokémon nomeados por geração[32]",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Geracao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f675d3f5-b773-4e5b-b17a-2571ea4c861e",
            "sourceColumn": "Geracao",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc02969e-7019-4fd7-9527-3a7362acc80c",
            "sourceColumn": "Value",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1e4da88f-712b-4eff-a4e2-43a5fe763a3d",
        "partitions": [
          {
            "name": "Lista de espécies Pokémon nomeados por geração[32]",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Web.BrowserContents(\"https://pt.wikipedia.org/wiki/Lista_de_Pok%C3%A9mon\"),",
                "    #\"Extracted Table From Html\" = Html.Table(Source, {{\"Column1\", \"TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(1):nth-last-child(9), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(17), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(16), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(14), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(13), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(12), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(11), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(10), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(9), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(8), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(6), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(5), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(4), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD[colspan=\"\"2\"\"][rowspan=\"\"5\"\"]:nth-child(1):nth-last-child(3)\"}, {\"Column2\", \"TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(1):nth-last-child(9), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(16), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(15), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(13), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(12), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(11), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(10), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(9), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(8), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(7), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(5), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(4), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(3), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD[colspan=\"\"2\"\"][rowspan=\"\"5\"\"]:nth-child(1):nth-last-child(3)\"}, {\"Column3\", \"TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(1):nth-last-child(9) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(2):nth-last-child(8), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(15), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(14), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(12), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(11), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(10), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(10) + TD[colspan=\"\"2\"\"][rowspan=\"\"56\"\"]:nth-child(3):nth-last-child(9)\"}, {\"Column4\", \"TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(1):nth-last-child(9) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(2):nth-last-child(8), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(14), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(13), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(12), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(11), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(10), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(9), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(10) + TD[colspan=\"\"2\"\"][rowspan=\"\"56\"\"]:nth-child(3):nth-last-child(9)\"}, {\"Column5\", \"TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(1):nth-last-child(9) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(2):nth-last-child(8) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(3):nth-last-child(7), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(13), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(12), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(11), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(10), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(9), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(8), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(10) + TD[colspan=\"\"2\"\"][rowspan=\"\"56\"\"]:nth-child(3):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(8), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(8), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(7), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(6), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(4), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(4) + TD[colspan=\"\"2\"\"][rowspan=\"\"21\"\"]:nth-child(3):nth-last-child(3)\"}, {\"Column6\", \"TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(1):nth-last-child(9) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(2):nth-last-child(8) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(3):nth-last-child(7), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TH:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(12), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(11), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(10), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(9), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(8), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(7), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(10) + TD[colspan=\"\"2\"\"][rowspan=\"\"56\"\"]:nth-child(3):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(7), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(7), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(6), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(5), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(4), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(3), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(4) + TD[colspan=\"\"2\"\"][rowspan=\"\"21\"\"]:nth-child(3):nth-last-child(3)\"}, {\"Column7\", \"TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(1):nth-last-child(9) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(2):nth-last-child(8) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(3):nth-last-child(7) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(4):nth-last-child(6), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TH:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13) + TH:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(12), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(12), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(11), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(10), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(9), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(8), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(7), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(6), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(10) + TD[colspan=\"\"2\"\"][rowspan=\"\"56\"\"]:nth-child(3):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(6), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(6), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(6) + TD[colspan=\"\"2\"\"][rowspan=\"\"59\"\"]:nth-child(5):nth-last-child(5)\"}, {\"Column8\", \"TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(1):nth-last-child(9) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(2):nth-last-child(8) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(3):nth-last-child(7) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(4):nth-last-child(6), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TH:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13) + TH:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(12) + TH:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(11), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(11), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(10), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(9), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(8), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(7), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(6), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(5), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(10) + TD[colspan=\"\"2\"\"][rowspan=\"\"56\"\"]:nth-child(3):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(5), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(5), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(6) + TD[colspan=\"\"2\"\"][rowspan=\"\"59\"\"]:nth-child(5):nth-last-child(5)\"}, {\"Column9\", \"TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(1):nth-last-child(9) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(2):nth-last-child(8) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(3):nth-last-child(7) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(4):nth-last-child(6) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(5):nth-last-child(5), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TH:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13) + TH:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(12) + TH:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(11) + TH:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(10), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(10), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(9), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(8), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(7), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(6), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(5), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(4), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(10) + TD[colspan=\"\"2\"\"][rowspan=\"\"56\"\"]:nth-child(3):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(4), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(4), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(6) + TD[colspan=\"\"2\"\"][rowspan=\"\"59\"\"]:nth-child(5):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(4), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(4), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(3), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(2), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(4) + TD[colspan=\"\"2\"\"][rowspan=\"\"21\"\"]:nth-child(3):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(2), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(2), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD[colspan=\"\"2\"\"][rowspan=\"\"5\"\"]:nth-child(1):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(2), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(2)\"}, {\"Column10\", \"TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(1):nth-last-child(9) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(2):nth-last-child(8) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(3):nth-last-child(7) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(4):nth-last-child(6) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(5):nth-last-child(5), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TH:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13) + TH:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(12) + TH:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(11) + TH:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(10) + TH:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(9), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(9), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(8), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(7), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(6), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(5), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(4), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(3), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(10) + TD[colspan=\"\"2\"\"][rowspan=\"\"56\"\"]:nth-child(3):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(3), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(3), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(6) + TD[colspan=\"\"2\"\"][rowspan=\"\"59\"\"]:nth-child(5):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(3), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(3), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(2), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(1), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(4) + TD[colspan=\"\"2\"\"][rowspan=\"\"21\"\"]:nth-child(3):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(1), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(1), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD[colspan=\"\"2\"\"][rowspan=\"\"5\"\"]:nth-child(1):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(1), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(1)\"}, {\"Column11\", \"TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(1):nth-last-child(9) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(2):nth-last-child(8) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(3):nth-last-child(7) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(4):nth-last-child(6) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(5):nth-last-child(5) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(6):nth-last-child(4), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TH:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13) + TH:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(12) + TH:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(11) + TH:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(10) + TH:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(9) + TH:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(8), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(8), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(8) + TD[colspan=\"\"2\"\"][rowspan=\"\"84\"\"]:nth-child(11):nth-last-child(7)\"}, {\"Column12\", \"TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(1):nth-last-child(9) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(2):nth-last-child(8) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(3):nth-last-child(7) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(4):nth-last-child(6) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(5):nth-last-child(5) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(6):nth-last-child(4), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TH:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13) + TH:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(12) + TH:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(11) + TH:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(10) + TH:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(9) + TH:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(8) + TH:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(7), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(7), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(8) + TD[colspan=\"\"2\"\"][rowspan=\"\"84\"\"]:nth-child(11):nth-last-child(7)\"}, {\"Column13\", \"TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(1):nth-last-child(9) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(2):nth-last-child(8) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(3):nth-last-child(7) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(4):nth-last-child(6) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(5):nth-last-child(5) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(6):nth-last-child(4) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(7):nth-last-child(3), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TH:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13) + TH:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(12) + TH:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(11) + TH:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(10) + TH:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(9) + TH:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(8) + TH:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(7) + TH:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(6), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(6), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(8) + TD[colspan=\"\"2\"\"][rowspan=\"\"84\"\"]:nth-child(11):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(6), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(6), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(6) + TD[colspan=\"\"2\"\"][rowspan=\"\"68\"\"]:nth-child(11):nth-last-child(5)\"}, {\"Column14\", \"TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(1):nth-last-child(9) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(2):nth-last-child(8) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(3):nth-last-child(7) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(4):nth-last-child(6) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(5):nth-last-child(5) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(6):nth-last-child(4) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(7):nth-last-child(3), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TH:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13) + TH:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(12) + TH:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(11) + TH:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(10) + TH:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(9) + TH:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(8) + TH:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(7) + TH:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(6) + TH:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(5), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(5), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(8) + TD[colspan=\"\"2\"\"][rowspan=\"\"84\"\"]:nth-child(11):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(5), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(5), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(6) + TD[colspan=\"\"2\"\"][rowspan=\"\"68\"\"]:nth-child(11):nth-last-child(5)\"}, {\"Column15\", \"TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(1):nth-last-child(9) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(2):nth-last-child(8) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(3):nth-last-child(7) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(4):nth-last-child(6) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(5):nth-last-child(5) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(6):nth-last-child(4) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(7):nth-last-child(3) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(8):nth-last-child(2), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TH:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13) + TH:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(12) + TH:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(11) + TH:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(10) + TH:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(9) + TH:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(8) + TH:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(7) + TH:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(6) + TH:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(5) + TH:not([colspan]):not([rowspan]):nth-child(15):nth-last-child(4), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(15):nth-last-child(4), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(8) + TD[colspan=\"\"2\"\"][rowspan=\"\"84\"\"]:nth-child(11):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(4), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(4), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(6) + TD[colspan=\"\"2\"\"][rowspan=\"\"68\"\"]:nth-child(11):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(4), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(4), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(4) + TD[colspan=\"\"2\"\"][rowspan=\"\"60\"\"]:nth-child(11):nth-last-child(3)\"}, {\"Column16\", \"TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(1):nth-last-child(9) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(2):nth-last-child(8) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(3):nth-last-child(7) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(4):nth-last-child(6) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(5):nth-last-child(5) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(6):nth-last-child(4) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(7):nth-last-child(3) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(8):nth-last-child(2), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TH:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13) + TH:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(12) + TH:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(11) + TH:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(10) + TH:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(9) + TH:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(8) + TH:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(7) + TH:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(6) + TH:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(5) + TH:not([colspan]):not([rowspan]):nth-child(15):nth-last-child(4) + TH:not([colspan]):not([rowspan]):nth-child(16):nth-last-child(3), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(15):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(16):nth-last-child(3), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(8) + TD[colspan=\"\"2\"\"][rowspan=\"\"84\"\"]:nth-child(11):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(15):nth-last-child(3), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(3), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(6) + TD[colspan=\"\"2\"\"][rowspan=\"\"68\"\"]:nth-child(11):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(3), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(3), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(4) + TD[colspan=\"\"2\"\"][rowspan=\"\"60\"\"]:nth-child(11):nth-last-child(3)\"}, {\"Column17\", \"TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(1):nth-last-child(9) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(2):nth-last-child(8) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(3):nth-last-child(7) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(4):nth-last-child(6) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(5):nth-last-child(5) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(6):nth-last-child(4) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(7):nth-last-child(3) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(8):nth-last-child(2) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(9):nth-last-child(1), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TH:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13) + TH:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(12) + TH:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(11) + TH:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(10) + TH:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(9) + TH:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(8) + TH:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(7) + TH:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(6) + TH:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(5) + TH:not([colspan]):not([rowspan]):nth-child(15):nth-last-child(4) + TH:not([colspan]):not([rowspan]):nth-child(16):nth-last-child(3) + TH:not([colspan]):not([rowspan]):nth-child(17):nth-last-child(2), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(15):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(16):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(17):nth-last-child(2), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(8) + TD[colspan=\"\"2\"\"][rowspan=\"\"84\"\"]:nth-child(11):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(15):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(16):nth-last-child(2), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(15):nth-last-child(2), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(6) + TD[colspan=\"\"2\"\"][rowspan=\"\"68\"\"]:nth-child(11):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(2), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(2), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(4) + TD[colspan=\"\"2\"\"][rowspan=\"\"60\"\"]:nth-child(11):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(2), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(2), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(10) + TD[colspan=\"\"2\"\"][rowspan=\"\"56\"\"]:nth-child(3):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(2), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(2), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(6) + TD[colspan=\"\"2\"\"][rowspan=\"\"59\"\"]:nth-child(5):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(2), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(2), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(2) + TD[colspan=\"\"2\"\"][rowspan=\"\"46\"\"]:nth-child(7):nth-last-child(1)\"}, {\"Column18\", \"TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(1):nth-last-child(9) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(2):nth-last-child(8) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(3):nth-last-child(7) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(4):nth-last-child(6) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(5):nth-last-child(5) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(6):nth-last-child(4) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(7):nth-last-child(3) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(8):nth-last-child(2) + TH[colspan=\"\"2\"\"]:not([rowspan]):nth-child(9):nth-last-child(1), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TH:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13) + TH:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(12) + TH:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(11) + TH:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(10) + TH:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(9) + TH:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(8) + TH:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(7) + TH:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(6) + TH:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(5) + TH:not([colspan]):not([rowspan]):nth-child(15):nth-last-child(4) + TH:not([colspan]):not([rowspan]):nth-child(16):nth-last-child(3) + TH:not([colspan]):not([rowspan]):nth-child(17):nth-last-child(2) + TH:not([colspan]):not([rowspan]):nth-child(18):nth-last-child(1), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(15):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(16):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(17):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(18):nth-last-child(1), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(8) + TD[colspan=\"\"2\"\"][rowspan=\"\"84\"\"]:nth-child(11):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(15):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(16):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(17):nth-last-child(1), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(15):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(16):nth-last-child(1), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(6) + TD[colspan=\"\"2\"\"][rowspan=\"\"68\"\"]:nth-child(11):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(15):nth-last-child(1), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(1), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(4) + TD[colspan=\"\"2\"\"][rowspan=\"\"60\"\"]:nth-child(11):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(1), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(1), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(10) + TD[colspan=\"\"2\"\"][rowspan=\"\"56\"\"]:nth-child(3):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(1), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(1), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(6) + TD[colspan=\"\"2\"\"][rowspan=\"\"59\"\"]:nth-child(5):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(1), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(1), TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(2) + TD[colspan=\"\"2\"\"][rowspan=\"\"46\"\"]:nth-child(7):nth-last-child(1)\"}}, [RowSelector=\"TABLE.wikitable.mw-collapsible:nth-child(21) > * > TR\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Extracted Table From Html\",{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}, {\"Column7\", type text}, {\"Column8\", type text}, {\"Column9\", type text}, {\"Column10\", type text}, {\"Column11\", type text}, {\"Column12\", type text}, {\"Column13\", type text}, {\"Column14\", type text}, {\"Column15\", type text}, {\"Column16\", type text}, {\"Column17\", type text}, {\"Column18\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Geração I\", type text}, {\"Geração I_1\", type text}, {\"Geração II\", type text}, {\"Geração II_2\", type text}, {\"Geração III\", type text}, {\"Geração III_3\", type text}, {\"Geração IV\", type text}, {\"Geração IV_4\", type text}, {\"Geração V\", type text}, {\"Geração V_5\", type text}, {\"Geração VI\", type text}, {\"Geração VI_6\", type text}, {\"Geração VII\", type text}, {\"Geração VII_7\", type text}, {\"Geração VIII\", type text}, {\"Geração VIII_8\", type text}, {\"Geração IX\", type text}, {\"Geração IX_9\", type text}}),",
                "    #\"Unpivoted Columns\" = Table.UnpivotOtherColumns(#\"Changed Type1\", {}, \"Attribute\", \"Value\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Unpivoted Columns\",{{\"Attribute\", \"Geracao\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_51553420-d6ff-41a6-b1dd-1687b339512f",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4b63bc91-6f93-48e7-a9ba-23b5d6a542a2",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "004a08cc-3e87-47af-b480-1c897e9d73c2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ae7f6307-e39a-40d8-95a3-2e98a9e40d2a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "1bcad38a-825d-4a3f-9777-46e89cc8cdac",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cb4ae486-b7e8-4a9d-9d8e-c18cbc1dc38c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "67af2ec1-ea39-4917-86a1-14131088409b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3980f887-ae3b-4239-890f-d5d6e455db50",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "cf51c650-ec36-42c6-9fb7-bf3d52045720",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "2b6f09e5-54e7-485f-ac92-8a2caec1187e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "46b64de0-5c58-4158-ac1d-e316f96bbf52",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "548ea7db-3f5a-474d-b213-c7d1e7d2b837",
                "ordinal": 3
              }
            ],
            "lineageTag": "c68f6ef4-9c3d-44c1-8089-c6b739a6a709"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "acd1e348-24b9-47ac-b192-0b47720f8c36",
        "partitions": [
          {
            "name": "DateTableTemplate_51553420-d6ff-41a6-b1dd-1687b339512f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Lista[editar | editar código-fonte]",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f1f4e4c-1b7a-421c-8b6b-2e3b3d4250d0",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          },
          {
            "name": "Posição",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3868f6a7-7ad2-4a84-a400-da426210a094",
            "sourceColumn": "Posição",
            "summarizeBy": "none"
          },
          {
            "name": "País (ou território dependente)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf3e43dd-9224-4cc3-a540-95de98bc43ff",
            "sourceColumn": "País (ou território dependente)",
            "summarizeBy": "none"
          },
          {
            "name": "Estimativa da ONU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b798de96-8b42-498b-9530-5152a41d6c5c",
            "sourceColumn": "Estimativa da ONU",
            "summarizeBy": "none"
          },
          {
            "name": "Crescimento desde a última estimativa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cfe241f3-17e2-4725-b13e-4cfc6fb3d43e",
            "sourceColumn": "Crescimento desde a última estimativa",
            "summarizeBy": "sum"
          },
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2002c530-d494-4ccf-b127-3b9f08fd87db",
            "sourceColumn": "Data",
            "summarizeBy": "sum"
          },
          {
            "name": "Estimativa Oficial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8db87a75-ed76-4776-b87b-c1aaf221f70c",
            "sourceColumn": "Estimativa Oficial",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a515a932-e989-48d3-829d-e844f3aede0e",
        "partitions": [
          {
            "name": "Lista[editar | editar código-fonte]",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Web.BrowserContents(\"https://pt.wikipedia.org/wiki/Lista_de_pa%C3%ADses_por_popula%C3%A7%C3%A3o\"),",
                "    #\"Extracted Table From Html\" = Html.Table(Source, {{\"Column1\", \"TABLE.wikitable.sortable > * > TR > :nth-child(1)\"}, {\"Column2\", \"TABLE.wikitable.sortable > * > TR > :nth-child(2)\"}, {\"Column3\", \"TABLE.wikitable.sortable > * > TR > :nth-child(3)\"}, {\"Column4\", \"TABLE.wikitable.sortable > * > TR > :nth-child(4)\"}, {\"Column5\", \"TABLE.wikitable.sortable > * > TR > :nth-child(5)\"}, {\"Column6\", \"TABLE.wikitable.sortable > * > TR > :nth-child(6)\"}, {\"Column7\", \"TABLE.wikitable.sortable > * > TR > :nth-child(7)\"}}, [RowSelector=\"TABLE.wikitable.sortable > * > TR\"]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Extracted Table From Html\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"\", type text}, {\"Posição\", type text}, {\"País (ou território dependente)\", type text}, {\"Estimativa da ONU\", type text}, {\"Crescimento desde a última estimativa\", Int64.Type}, {\"Data\", Int64.Type}, {\"Estimativa Oficial\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Table 4",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Bandeira",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d56e8dd-0d32-4142-ad1c-31cf6146e48b",
            "sourceColumn": "Bandeira",
            "summarizeBy": "none"
          },
          {
            "name": "Estado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "31bdc31c-40b1-48c1-97f3-d526d93e6ac3",
            "sourceColumn": "Estado",
            "summarizeBy": "none"
          },
          {
            "name": "Sigla",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1481a813-f4fd-4241-9c38-f517e73f2929",
            "sourceColumn": "Sigla",
            "summarizeBy": "none"
          },
          {
            "name": "Capital",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c8cfb788-a7c4-48ae-b0cb-b52e520f7d5b",
            "sourceColumn": "Capital",
            "summarizeBy": "none"
          },
          {
            "name": "Região",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "987a2492-8a07-482a-8dcc-c5c4362be8f4",
            "sourceColumn": "Região",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a6a06afd-6453-49a0-98ea-0c4831dabfd0",
        "partitions": [
          {
            "name": "Table 4",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Web.BrowserContents(\"https://www.estadosecapitaisdobrasil.com/\"),",
                "    #\"Extracted Table From Html\" = Html.Table(Source, {{\"Column1\", \"TABLE.table.table-striped.text-center > * > TR > :nth-child(1)\"}, {\"Column2\", \"TABLE.table.table-striped.text-center > * > TR > :nth-child(2)\"}, {\"Column3\", \"TABLE.table.table-striped.text-center > * > TR > :nth-child(3)\"}, {\"Column4\", \"TABLE.table.table-striped.text-center > * > TR > :nth-child(4)\"}, {\"Column5\", \"TABLE.table.table-striped.text-center > * > TR > :nth-child(5)\"}}, [RowSelector=\"TABLE.table.table-striped.text-center > * > TR\"]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Extracted Table From Html\", [PromoteAllScalars=true])",
                "in",
                "    #\"Promoted Headers\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}